modLoader="javafml"
loaderVersion="[43,)"
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/TerraformersMC/Campanion/issues"
[[mods]]
modId="campanion"
version="${file.jarVersion}"
displayName="Campanion"
logoFile="assets/campanion/logo.png"
authors="Wyn Price, NeusFear, Prospector, TerraformersMC"
description='''
A camping companion that adds items and utilities to improve your life away from home.
'''

[[dependencies.campanion]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.multiloader]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
